---
apiVersion: v1
kind: Service
metadata:
  name: validatepassword
spec:
  selector:
    app: validatepassword
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validatepassword
spec:
  replicas: 2
  selector:
    matchLabels:
      app: validatepassword
  template:
    metadata:
      labels:
        app: validatepassword
    spec:
      containers:
        - name: netcore
          image: caiowillian/validatepassword:2
